// Generated by delombok at Sat Jun 24 22:59:11 EDT 2017
package com.dellaria.demos.nluwatson;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "NLU")
public class NLU {
	@Column(name = "Id")
	@Id
	@GeneratedValue
	private Long id;
	@Column(name = "filename")
	private String filename;
	@Column(name = "item") //Concept, entity, keyword, category
	private String item;	
	@Column(name = "itemtext")
	private String itemtext;
	@Column(name = "type")
	private String type;
	@Column(name = "relevance") // relevance. score
    public Double relevance;
	@Column(name = "count")
    public long count;
	@Column(name = "year")
    public int year;
	@Column(name = "sentiment")
    public Double sentiment;
	@Column(name = "anger")
    public Double anger;
	@Column(name = "disgust")
    public Double disgust;
	@Column(name = "fear")
    public Double fear;
	@Column(name = "joy")
    public Double joy;
	@Column(name = "sadness")
    public Double sadness;

	public NLU() {
	}



	public NLU(String filename, String item, String itemtext,String type, Double relevance, long count, int year, Double sentiment,
			Double anger, Double disgust, Double fear, Double joy, Double sadness) {
		this.filename = filename;
		this.item = item;
		this.itemtext = itemtext;
		this.type = type;
		this.relevance = relevance;
		this.count = count;
		this.year = year;
		this.sentiment = sentiment;
		this.anger = anger;
		this.disgust = disgust;
		this.fear = fear;
		this.joy = joy;
		this.sadness = sadness;
	}


}
// end::code[]